# EDA Process

### Importing Libraries 

In [24]:
# Importing Libraries 
import numpy as np   ## used for Stastics
import pandas as pd ## used for dataframes

### Load the  Resturant Review dataset

In [40]:
dataset = pd.read_csv('E:/nikhitha/datasets/Restaurant_Reviews.tsv', delimiter = '\t') 


### Finding dimensions of dataset 

In [41]:
dataset.shape

(1000, 2)

### Getting all the rows

### Importing the nltk package natural language tool kit

In [26]:
# Natural Language Tool Kit 
import nltk  # natural language tool kit

In [5]:
# dataset['Review'] = dataset['Review'].str.lower()


In [27]:
dataset.head()
dataset['Review'][10]

'Service was very prompt.'

### Cleaning the text data removing other special characters

In [42]:
import re
def clean(text):
    review = re.sub('[^a-zA-Z]', ' ', text)
    #review =  [re.sub('[^a-zA-Z]','@', text)]
    return review


dataset['Review']=dataset['Review'].apply(lambda x : clean(x))


In [29]:
print(dataset['Review'][2])

Not tasty and the texture was just nasty 


### Dividing the sentences into words called tokens

In [43]:
from nltk.tokenize import TreebankWordTokenizer 
tokenizer = TreebankWordTokenizer() 
def token(text):
    review = tokenizer.tokenize(text)
#     review = [tokenizer.tokenize(text)]
    return review

dataset['Review']=dataset['Review'].apply(lambda x : token(x))

In [10]:
print(dataset['Review'][0])

['Wow', 'Loved', 'this', 'place']


### Lemmatizing the words removing the suffixes

In [44]:
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()
def lematizer(text):
    review = [lemmatizer.lemmatize(i) for i in text]
    return review
    
dataset['Review']=dataset['Review'].apply(lambda x : lematizer(x))


In [12]:
print(dataset['Review'][0])

['Wow', 'Loved', 'this', 'place']


In [13]:
print(dataset['Review'][1])

['Crust', 'is', 'not', 'good']


### Removing the Stop words

In [45]:
from nltk.corpus import stopwords
def stop_word(text):
    #stopwords=get_stop_words("resources/stopwords.txt")
    review = [i for i in text if i not in stopwords.words('english')]
    return review

dataset['Review']=dataset['Review'].apply(lambda x : stop_word(x))

In [15]:
print(dataset['Review'][0])

['Wow', 'Loved', 'place']


### Converting words to lower case 

In [48]:
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer(lowercase=True,max_df = 0.50, stop_words=stopwords.words('english'))

from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
#from nltk.stem import WordNetLemmatizer 
#from nltk.tokenize import TreebankWordTokenizer
#lemmatizer = WordNetLemmatizer(text)
# token = TreebankWordTokenizer() 
# def token(text):
#     review = token.tokenize
# #     review = [tokenizer.tokenize(text)]
#     return review
#tokenizer to remove unwanted elements from out data like symbols and numbers
#token = RegexpTokenizer(r'[a-zA-Z0-9]+')
#dataset['Review'] = dataset['Review'].str.lower()
cv = CountVectorizer(lowercase=True)
word_count_vector = cv.fit_transform(dataset['Review'])

In [49]:
dataset["Review"]

0                              ['Wow', 'Loved', 'place']
1                                      ['Crust', 'good']
2             ['Not', 'tasty', 'texture', 'wa', 'nasty']
3      ['Stopped', 'late', 'May', 'bank', 'holiday', ...
4      ['The', 'selection', 'menu', 'wa', 'great', 'p...
5      ['Now', 'I', 'getting', 'angry', 'I', 'want', ...
6                 ['Honeslty', 'taste', 'THAT', 'fresh']
7      ['The', 'potato', 'like', 'rubber', 'could', '...
8                                ['The', 'fry', 'great']
9                                ['A', 'great', 'touch']
10                           ['Service', 'wa', 'prompt']
11                               ['Would', 'go', 'back']
12     ['The', 'cashier', 'care', 'ever', 'I', 'say',...
13     ['I', 'tried', 'Cape', 'Cod', 'ravoli', 'chick...
14     ['I', 'wa', 'disgusted', 'I', 'wa', 'pretty', ...
15     ['I', 'wa', 'shocked', 'sign', 'indicate', 'ca...
16                             ['Highly', 'recommended']
17       ['Waitress', 'wa', 'li

In [47]:
#p_test = pd.read_csv('TrainSA.csv')
dataset.Review=dataset.Review.astype(str)

In [52]:
list(cv.vocabulary_.keys())[:10]

['wow',
 'loved',
 'place',
 'crust',
 'good',
 'not',
 'tasty',
 'texture',
 'wa',
 'nasty']

In [53]:
y = dataset.iloc[:, 1].values 

In [54]:
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [58]:
# Splitting the dataset into 
# the Training set and Test set 
from sklearn.model_selection import train_test_split

#X_train, X_test, y_train, y_test = train_test_split(processed_features, labels, test_size=0.2, random_state=0)
#from sklearn.cross_validation import train_test_split 
  
# experiment with "test_size" 
# to get better results 
X_train, X_test, y_train, y_test = train_test_split(word_count_vector, y, test_size = 0.25) 

In [59]:
from sklearn.ensemble import RandomForestClassifier 
  
# n_estimators can be said as number of 
# trees, experiment with n_estimators 
# to get better results  
model = RandomForestClassifier(n_estimators = 501, 
                            criterion = 'entropy') 
                              
model.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=501, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [60]:
y_pred = model.predict(X_test) 
  
y_pred 

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1], dtype=int64)

In [63]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[106  24]
 [ 35  85]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78       130
           1       0.78      0.71      0.74       120

   micro avg       0.76      0.76      0.76       250
   macro avg       0.77      0.76      0.76       250
weighted avg       0.77      0.76      0.76       250

0.764
